apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserverhello-deployment
spec:
  selector:
    matchLabels:
      app: webserverhello
  template: 
    metadata:
      labels:
        app: webserverhello
    spec:
      containers:
        - name: webserverhello-container
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          env:
            - name: TITLE
              value: 'Hello students app1'
---
---
apiVersion: v1
kind: Service
metadata:
  name: webserverhello-service
spec:
  selector:
    app: webserverhello
  ports:
    - port: 80
      targetPort: 80